### PR TITLE
Action Server Feedback on Timer

### PR DESCRIPTION
**Pull request by p6chen**
@jasonimercer @skaynama @servos

### CODE REVIEW

**Comment by jasonimercer** [comment]
You should call .stop() on your new timer in the destructor before as_ is deleted.

**Comment by jasonimercer** [comment]
other than that, LGTM

**Comment by skaynama** [comment]
LGTM

**Comment by servos** [comment]
:+1:

**Comment by skaynama** [comment]
@abencz  can you please check if this addresses your concern?

**Comment by abencz** [comment]
LGTM

**Pull request merged**
