### PR TITLE
Removing references to AxisAlignedBoundingBox, DynamicAlgorithmSelect, and LayerActions

### PR DESCRIPTION
**Pull request by ayrton04**
Also did some minor space removal cleanup. @skaynama @jasonimercer

### CODE REVIEW

**Comment by ayrton04** [comment]
Oh, I also reverted all the layer plugins to their upstream versions.

**Comment by jasonimercer** [comment]
It looks reasonable. Will need to do some sanity testing just before merging into devel. 

LGTM

**Comment by skaynama** [comment]
LGTM.

**Comment by ayrton04** [comment]
Yeah, I plan to spend a lot of time testing all of this before the final merge. Thanks all!

**Pull request merged**
