### PR TITLE
Removed the automatic conversion of goals to the global frame by move…

### PR DESCRIPTION
**Pull request by p6chen**
…_base. This allows goals to be passed straight to the planners in the desired frame of reference.

@jasonimercer @skaynama @servos @schopra01

### CODE REVIEW

**Comment by p6chen** [comment]
Sibling PR: https://bitbucket.org/clearpathrobotics/strategy_management/pull-requests/190/pass-docking-goal-in-local-frame/diff

**Comment by skaynama** [comment]
LGTM

**Comment by jasonimercer** [comment]
LGTM

**Comment by servos** [comment]
👍

**Pull request merged**
