### PR TITLE
CORE-1711

### PR DESCRIPTION
**Pull request by jasonimercer**
Removed unsigned restriction from many window ranges to allow for coordinates like (-5,-5) to be input and auto-clamped to (0,0).

Fixed range check in Costmap2D::setMapCost()

### CODE REVIEW

**Comment by jasonimercer** [comment]
@skaynama @servos

**Comment by jasonimercer** [comment]
Small PR. Quality of life changes and range check fix.

**Comment by servos** [comment]
As long as passing negative numbers is handled correctly in each case (I only checked briefly) this LGTM.

**Comment by skaynama** [comment]
Why is that necessary if you're going to clamp negative values to 0 anyway?

**Comment by jasonimercer** [comment]
Sometimes you're working with a window of data and you want to expand it with a border. This may push it into negative coordinates.

**Comment by skaynama** [comment]
LGTM

**Pull request merged**
