### PR TITLE
Fixed problem related to costmap resize where the mutex was not

### PR DESCRIPTION
**Pull request by jasonimercer**
acquired before the variables managing size were altered. Added in child map clears when the base costmap was resized or had the origin changed.

Several calls to initMaps or deleteMaps were converted to the actual code so the same mutex could guard all actions.

CORE-1735

### CODE REVIEW

**Comment by jasonimercer** [comment]
@servos @paulbovbel

**Comment by paulbovbel** [comment]
A little confused - it looks like you're repeating a lot of code. Why can't you use a common method that includes the mutex lock?

**Comment by paulbovbel** [comment]
Ah I get why. Take a look at the way this has been fixed upstream https://github.com/ros-planning/navigation/blob/jade-devel/costmap_2d/include/costmap_2d/costmap_2d.h#L294

**Comment by jasonimercer** [comment]
Yeah, the recursive mutex does give more flexibility. I need to fix merge conflicts - I could use this opportunity to switch mutex types throughout costmap_2d.

**Comment by skaynama** [comment]
Just catching up with things. While we're at it, can we try and merge our changes upstream so we can stay updated with their changes? For e.g. footprint layer is now part of the obstacle layer (?), or the fix for a potential deadlock in dynamic reconfigure of the base_global_planner, etc.

**Comment by jasonimercer** [comment]
Yeah, I'm using this opportunity to bring us in line with upstream.

**Comment by skaynama** [comment]
Is this ever going to get merged in?

**Comment by jasonimercer** [comment]
This should get closed. PR 23 makes many of the changes this has and more. 

Once PR 23 gets accepted I'll work through the map loading code path and ensure it's safe, otherwise I'll make a new branch that implements the ideas here. That should end up being a very small PR.

**Pull request closed without merging**
