### PR TITLE
Adding service calls the indicate that recovery execution has completed

### PR DESCRIPTION
**Pull request by ayrton04**
FYI @jasonimercer @skaynama @p6chen. See my forthcoming PRs for this ticket for more information.

### CODE REVIEW

**Comment by skaynama** [comment]
Remind me again where would be the callback function for this service call?

Wouldn't a service call within the same node have the potential to result in a deadlock?

Why not use the existing pointer and a setter/getter function? Specifically, after ```recovery_behaviors_[recovery_index_]->runBehavior();``` is executed you could do something like ```recovery_behaviors_[recovery_index_]->completed();``` where a flag is set.

**Comment by ayrton04** [comment]
Will respond offline.

**Comment by ayrton04** [comment]
OK, take two. @skaynama @jasonimercer @p6chen

**Comment by skaynama** [comment]
LGTM.

**Comment by jasonimercer** [comment]
LGTM

**Pull request merged**
