### PR TITLE
Removed planning related costmap lock from higher level

### PR DESCRIPTION
**Pull request by jasonimercer**
and documented requirement of lower level to lock the map as required.

@p6chen 
@servos 
@ayrton04 
@chandel01 
@skaynama

### CODE REVIEW

**Comment by servos** [comment]
LGTM, be sure to test thoroughly since removing a mutex is always a dangerous game.

**Comment by ayrton04** [comment]
After an offline chat with Jason, this LGTM.

**Comment by p6chen** [comment]
lgtm

**Comment by jasonimercer** [comment]
Adding documentation so reviewers of this change down the road know the context:

Moving the mutex lock down to the level where the data is accessed allows the mutex to be released as soon as safely possible.  This allows the global costmap to continue to get map updates and publish changes to clients. Without this change a planning cycle that takes (lets say) 60 minutes would not allow the states of the costmap plugin layers to be changed or the costmap itself to be changed to reflect any dynamics.

**Comment by skaynama** [comment]
LGTM.

**Pull request merged**
