### PR TITLE
CORE-3611: Add >= check in addition to setting planner_patience to 0.…

### PR DESCRIPTION
**Pull request by chandel01**
… This ensures that after a loop of death is detected, we invoke recovery.

@skaynama, @jasonimercer , @p6chen

### CODE REVIEW

**Comment by skaynama** [comment]
For context, this helps when ```planner_patience``` is set to zero.  LGTM.

**Comment by jasonimercer** [comment]
LGTM

**Comment by p6chen** [comment]
lgtm

**Comment by chandel01** [comment]
merged.

**Pull request merged**
