### PR TITLE
Core 3163 move base goal manager

### PR DESCRIPTION
**Pull request by jasonimercer**
Adding a mechanism to share the validity/activeness of the current goal so that planners and recovery strategies can stop running.

### CODE REVIEW

**Comment by jasonimercer** [comment]
@skaynama @p6chen 

This works in conjunction with an upcoming PR in pathtracker.

**Comment by skaynama** [comment]
Code wise it LGTM. Two things to consider before merging:

1. How does this interact with the logic that was added to line 669 (do Blame to see what was done) to react to a new goal when we are churning in ```makePlan``` based on the old goal.

2. Implications of adding a proprietary license header to a BSD package.

**Comment by p6chen** [comment]
lgtm code wise.

**Comment by jasonimercer** [comment]
I made some changes to this PR. I'm preserving Tom's fixes for changed goal race condition as there's still a window with preemption where it could trigger. Updated logic to use goal manager pose compares. Changed the license to BSD for the goal manager in nav_core.

**Comment by skaynama** [comment]
LGTM.

**Pull request merged**
